project: Basic CI Pipeline
stages:
  - stage: setup
    command: make setup
  - stage: .env copy
    command: cp .env.template .env
  - stage: typecheck
    command: make typecheck
  - stage: run tests
    command: make test
  - stage: build
    command: make build